## Data was generated by Ruben Herzog and exported as numpy files (.npy)
# The exported data has shape (n_features, n_samples) and is stored in the following files:
# [tt|hh]_<distribution_name>_alpha-<alpha_value>.npy
# The data must be exporded into csv formal with transposed shape (n_samples, n_features) and stored in the following files:
# [tt|hh]_<distribution_name>_alpha-<alpha_value>.csv
#
# Also, the joint data to do the analysis of O(TT+HH) == O(TT) + O(HH) is created by concatenating the two data sets (tt and hh) of each distribution and stored in the following files:
# joint_<distribution_name>_alpha-<alpha_value>_joint.csv

python npy2csv.py --npy_file_dir /home/laouen.belloli/Documents/data/PGM_data
python join_distributions.py --file_paths /home/laouen.belloli/Documents/data/PGM_data